name: Run build, test & publish

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
  pull_request:
    paths:
      - 'packages/**'
      - 'internal/**'
      - 'pnpm.lock'
      - 'package.json'
      - 'turbo.json'

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: contains(github.event.pull_request.title, ':tada:') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-js-workflow
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      # - name: Build and check size
      #   if: github.ref_type == 'pull_request'
      #   uses: andresz1/size-limit-action@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     skip_step: install
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      #     TURBO_TOKEN: turbotoken-oss-europe1

      - name: Build
        run: pnpm build
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          TURBO_TOKEN: turbotoken-oss-europe1

  test:
    if: contains(github.event.pull_request.title, ':tada:') == false
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-js-workflow
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Test
        run: pnpm test
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          TURBO_TOKEN: turbotoken-oss-europe1

  lint:
    if: contains(github.event.pull_request.title, ':tada:') == false
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-js-workflow
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Lint
        run: pnpm lint
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          TURBO_TOKEN: turbotoken-oss-europe1

  publish:
    if: contains(github.ref_name, 'develop') || contains(github.ref_name, 'main')
    needs: [build, test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Set job params
        shell: bash
        id: deployment-params
        run: |
          echo "version=$([ "${{ github.ref_name }}" = "main" ] && echo "version-release" || echo "version-development")" >> $GITHUB_OUTPUT
          echo "publishName=$([ "${{ github.ref_name }}" = "main" ] && echo "Release" || echo "Pre-Release")" >> $GITHUB_OUTPUT

      - name: "Create Pull Request or Publish to npm"
        uses: changesets/action@v1
        with:
          title: ":tada: Publish pre-release"
          version: pnpm ${{ steps.deployment-params.outputs.version }}
          publish: pnpm publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
